---
spring:
  profile: dev
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://zyw:8001/arrange?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: arrange
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enable: true
      stat-view-servlet:
        enabled: true
        login-username: druid_admin
        login-password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
...

---
swagger-api:
  enable: true
...

---
server:
  port: 10010
  tomcat:
    max-threads: 1000
    min-spare-threads: 5
    max-connections: 50
    connect-timeout: 30000
    max-keepalive: 10000
  management:
    port: 10011
    health:
      db:
        enabled: true
      mail:
        enabled: true
    security:
      enabled: false
...